bagisto/headless-ecommerce

packages/Webkul/GraphQLAPI/Mutations/Setting/CustomScriptMutation.php, packages/Webkul/GraphQLAPI/Resources/lang/en/app.php, packages/Webkul/GraphQLAPI/graphql/setting/custom_script.graphql
=> added api for custom scripts #37

src/Queries/Catalog/ProductContent.php, src/graphql/catalog/product.graphql
- Added currency without currency code also. Needed for vercel commerce.
=> Currency Added Without Currency Code

src/Queries/Shop/Product/ProductListingQuery.php, src/graphql/shop/product/product.graphql
- Needed query for product fetching by slug.
=> Product By Slug Query Added

src/Queries/Shop/Customer/CustomerOrderQuery.php, src/graphql/shop/customer/orders.graphql
- Fixed order authentication issue.
- Fixed paginator instance.
=> Fixed Order Authentication

src/Queries/Shop/Product/ProductListingQuery.php, src/graphql/shop/product/item_listing.graphql
- New and featured check added as sorting can only be possible from here.
=> New And Featured Check Added

src/Queries/Catalog/ProductContent.php, src/Queries/Shop/Product/ProductListingQuery.php
- Configurable product attribute options null case handled and added configurable type.
=> Configurable Product Attribute Options Null Case Handled And Added Configurable Type

src/Providers/GraphQLAPIServiceProvider.php
$this->publishes([__DIR__.'/../graphql/schema.graphql' => base_path('graphql/schema.graphql')]);
pulbic graphql schema
=> uodate code in  GraphQLAPIServiceProvider 

CHANGELOG.md, src/Cart.php, src/Models/BookingProduct/BookingProduct.php, src/Models/Setting/CurrencyExchangeRate.php, src/Models/User/Admin.php, src/Queries/BaseFilter.php
initial push compatibility for v1.4.3(not fully tested yet)
=> initial push compatibility for v1.4.3(not fully tested yet)

CHANGELOG.md
=> Changelog Updated for V2.0.0

src/Config/system.php, src/Mutations/Shop/Customer/CheckoutMutation.php, src/Repositories/NotificationRepository.php, src/Resources/lang/ar/app.php, src/Resources/lang/en/app.php, src/Resources/lang/es/app.php, src/Resources/lang/fr/app.php, src/Resources/lang/hi_IN/app.php, src/Resources/lang/ja/app.php, src/Resources/lang/nl/app.php, src/Resources/lang/tr/app.php
Update Firebase notification with oAuth2.0 security
=> update firebase notification

src/Queries/Shop/Common/HomePageQuery.php
>Minor Issue Fixed [Theme Customization]
=> Minor Issue Fixed [Theme Customization]

Postman_APIs/Collections/GraphQL-API.postman_collection.json, src/BagistoGraphql.php, src/graphql/common.graphql, src/graphql/schema.graphql
>Type (Paginator Info) Issue Fixed
=> Type (Paginator Info) Issue Fixed

src/Mutations/Admin/Customer/CustomerAddressMutation.php, src/Mutations/Admin/Sales/Reorder/ReorderMutation.php, src/Mutations/Shop/Customer/AddressesMutation.php, src/Mutations/Shop/Customer/CheckoutMutation.php, src/Queries/Shop/Common/TaxQuery.php
Fixed Postcode and country state issue
=> [2.3] Fixed Postcode and country state issue

README.md, src/Mutations/Shop/Customer/CartMutation.php
> Compatibility with the Bagisto v2.3.0
=> Compatibility with the Bagisto v2.3.0

README.md, src/Mutations/Shop/Customer/CartMutation.php
> Refactor middleware handling in CartMutation and update README for installation steps
=> Refactor middleware handling in CartMutation and update README for installation steps

.github/ISSUE_TEMPLATE/bug.yml, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.yml
> Add issue templates for bug reports and feature requests
=> Add issue templates for bug reports and feature requests

src/Mutations/Shop/Customer/AddressesMutation.php
=> Fixed issue #370

src/Mutations/Shop/Customer/AccountMutation.php
=> Fixed issue #368

src/Mutations/Admin/Customer/CustomerMutation.php
=> Fixed issue #364

src/graphql/admin/catalog/products/product.graphql
> Add customizable options to Product type in GraphQL schema
=> Add customizable options to Product type in GraphQL schema

src/graphql/admin/catalog/products/product.graphql
>Enhance ProductCustomizableOption type with label and translations fields
=> Enhance ProductCustomizableOption type with label and translations fields

src/Database/Migrations/2025_06_02_173912_alter_customers_table.php, src/Mutations/Shop/Customer/SessionMutation.php, src/Repositories/NotificationRepository.php, src/graphql/common.graphql
=> OrderNotification

README.md, src/Config/graphiql.php, src/Config/lighthouse.php, src/Http/Requests/NotificationRequest.php, src/Listeners/SetCacheQuery.php, src/Queries/Shop/Common/HomePageQuery.php, src/Services/GraphQLCacheService.php, src/graphql/schema.graphql, src/graphql/shop/cart/cart_payment.graphql, src/graphql/shop/common/gdpr.graphql, src/graphql/shop/common/learn-more-and-customize.graphql
> Update README and configuration files for GraphQL API installation and performance improvements
=> Update README and configuration files for GraphQL API installation

Postman_APIs/Collections/GraphQL-API.postman_collection.json
> Update Postman collection to reflect GDPR configuration changes
=> Update Postman collection to reflect GDPR configuration changes

src/Http/Middleware/GraphQLCacheMiddleware.php, src/Listeners/ClearCache.php, src/Providers/EventServiceProvider.php
> Fix: Cache not invalidating after theme customization or product delete
=> Fix: Cache not invalidating after theme customization or product delete

src/Console/Commands/Install.php, src/DataGrids/PushNotificationDataGrid.php, src/Mutations/Shop/Customer/OrderMutation.php
> refactor: Update PushNotificationDataGrid to use app locale and add return types
> fix: Enhance order cancellation logic in OrderMutation to ensure correct order retrieval
=> refactor: Improvement

README.md, src/Providers/GraphQLAPIServiceProvider.php
> Revert "Compatibility to v2.3.6"
=> Revert "Compatibility to v2.3.6"

src/Models/PushNotification.php, src/Models/PushNotificationTranslation.php, src/Mutations/Admin/Setting/ThemeMutation.php, src/Providers/GraphQLAPIServiceProvider.php, src/Resources/lang/ar/app.php, src/Resources/lang/bn/app.php, src/Resources/lang/ca/app.php, src/Resources/lang/de/app.php, src/Resources/lang/en/app.php, src/Resources/lang/es/app.php, src/Resources/lang/fa/app.php, src/Resources/lang/fr/app.php, src/Resources/lang/he/app.php, src/Resources/lang/hi_IN/app.php, src/Resources/lang/id/app.php, src/Resources/lang/it/app.php, src/Resources/lang/ja/app.php, src/Resources/lang/nl/app.php, src/Resources/lang/pl/app.php, src/Resources/lang/pt_BR/app.php, src/Resources/lang/ru/app.php, src/Resources/lang/sin/app.php, src/Resources/lang/tr/app.php, src/Resources/lang/uk/app.php, src/Resources/lang/zh_CN/app.php, src/Routes/fcm-routes.php
=> Issue Fixing v2.3.6
